In [1]:
import numpy as np

In [ ]:
array = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
print(array)

[[1 2 3]
 [4 5 6]]


In [11]:
arr = np.array([
    [2, 2, 2], 
    [4, 5, 6], 
    [0.1, 0.2, 0.5], 
    [3, -7, 0.3]
    ])

In [12]:
print(arr)

[[ 2.   2.   2. ]
 [ 4.   5.   6. ]
 [ 0.1  0.2  0.5]
 [ 3.  -7.   0.3]]


In [13]:
arr2 = arr[:2,::2]
print("First two rows and alternate columns:\n",arr2)

First two rows and alternate columns:
 [[2. 2.]
 [4. 6.]]


In [16]:
print("Add 1 to every element:\n",arr2+1)

Add 1 to every element:
 [[3. 3.]
 [5. 7.]]


In [17]:
arr2=arr2+1
print("After adding 1:\n",arr2)

After adding 1:
 [[3. 3.]
 [5. 7.]]


In [18]:
print("Subtract 2 from every element:\n",arr2-2)

Subtract 2 from every element:
 [[1. 1.]
 [3. 5.]]


In [19]:
print("Sum of array elements:", np.sum(arr2))

Sum of array elements: 18.0


In [21]:
arr3 = np.array([[2, 3], [5, 6]])
print(arr3)

[[2 3]
 [5 6]]


In [23]:
print(arr2*arr3)

[[ 6.  9.]
 [25. 42.]]
